# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/excel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(90, 20, 312, 81))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.layout_id_requisitante = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.layout_id_requisitante.setContentsMargins(0, 0, 0, 0)
        self.layout_id_requisitante.setSpacing(0)
        self.layout_id_requisitante.setObjectName("layout_id_requisitante")
        self.lbl_numero = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_numero.sizePolicy().hasHeightForWidth())
        self.lbl_numero.setSizePolicy(sizePolicy)
        self.lbl_numero.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_numero.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_numero.setFont(font)
        self.lbl_numero.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_numero.setObjectName("lbl_numero")
        self.layout_id_requisitante.addWidget(self.lbl_numero)
        self.spb_numero = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.spb_numero.setMinimumSize(QtCore.QSize(310, 30))
        self.spb_numero.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spb_numero.setFont(font)
        self.spb_numero.setStyleSheet("outline: none;\n"
"border: 1px solid red;")
        self.spb_numero.setAlignment(QtCore.Qt.AlignCenter)
        self.spb_numero.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spb_numero.setMaximum(1000000)
        self.spb_numero.setProperty("value", 0)
        self.spb_numero.setObjectName("spb_numero")
        self.layout_id_requisitante.addWidget(self.spb_numero)
        self.btn_deletar = QtWidgets.QPushButton(Form)
        self.btn_deletar.setGeometry(QtCore.QRect(180, 440, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_deletar.sizePolicy().hasHeightForWidth())
        self.btn_deletar.setSizePolicy(sizePolicy)
        self.btn_deletar.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_deletar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_deletar.setFont(font)
        self.btn_deletar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deletar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_deletar.setStyleSheet("background: rgb(255, 0, 0);\n"
"color: white;")
        self.btn_deletar.setFlat(False)
        self.btn_deletar.setObjectName("btn_deletar")
        self.tbl_planilha = QtWidgets.QTableWidget(Form)
        self.tbl_planilha.setGeometry(QtCore.QRect(15, 131, 471, 271))
        self.tbl_planilha.setStyleSheet("outline:red;")
        self.tbl_planilha.setFrameShape(QtWidgets.QFrame.Box)
        self.tbl_planilha.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_planilha.setAutoScroll(True)
        self.tbl_planilha.setTabKeyNavigation(True)
        self.tbl_planilha.setProperty("showDropIndicator", True)
        self.tbl_planilha.setShowGrid(True)
        self.tbl_planilha.setWordWrap(True)
        self.tbl_planilha.setCornerButtonEnabled(True)
        self.tbl_planilha.setRowCount(0)
        self.tbl_planilha.setColumnCount(0)
        self.tbl_planilha.setObjectName("tbl_planilha")
        self.tbl_planilha.horizontalHeader().setVisible(True)
        self.tbl_planilha.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_planilha.horizontalHeader().setHighlightSections(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Deletar Hospedagem"))
        self.lbl_numero.setText(_translate("Form", "NÚMERO"))
        self.btn_deletar.setText(_translate("Form", "DELETAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
